### ISSUE TITLE
export sim to AUTO

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#65] opened 2017-02-01 15:08 UTC
I think this program would be a good linker:
http://www.warrenweckesser.net/vfgen/

it takes a simple XML document that could easily be written by dynasim, and convert to: Scilab, AUTO, GNU Scientific Library, SciPy, PyDSTool, XPP among others

**Comment by jsherfey** [comment] 2017-10-21 07:38
This is a duplicate of Issue #5.

**Closed** 2017-10-21 07:37 UTC
Labels: enhancement
