### ISSUE TITLE
Random seed mode is not random when in parallel mode 

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#311] opened 2017-12-08 01:54 UTC
Setting 'random_seed' to 'shuffle' doesn't produce random outputs across parfor workers. However, it does in serial mode. This is useful when you want to measure averages across many simulations in the presence of noise. 

This is a continuation of issue #297. The changes in #297 didn't fix the problem.

**Comment by davestanley** [comment] 2017-12-08 02:14
Here is the code I'm using to test this. The parameter `myshuffle` in the vary statement is a dummy parameter to force it to run multiple simulations.

```
%% Simulate Sparse Pyramidal-Interneuron-Network-Gamma (sPING)

% define equations of cell model (same for E and I populations)
eqns={
  'dv/dt=Iapp+@current+noise*randn(1,N_pop); Iapp=0; noise=0'
  'monitor iGABAa.functions, iAMPA.functions'
};
% Tip: monitor all functions of a mechanism using: monitor MECHANISM.functions

% create DynaSim specification structure
s=[];
s.populations(1).name='E';
s.populations(1).size=10;
s.populations(1).equations=eqns;
s.populations(1).mechanism_list={'iNa','iK'};
s.populations(1).parameters={'Iapp',5,'gNa',120,'gK',36,'noise',40};
s.populations(2).name='I';
s.populations(2).size=10;
s.populations(2).equations=eqns;
s.populations(2).mechanism_list={'iNa','iK'};
s.populations(2).parameters={'Iapp',0,'gNa',120,'gK',36,'noise',10};
s.connections(1).direction='I->E';
s.connections(1).mechanism_list={'iGABAa'};
s.connections(1).parameters={'tauD',10,'gSYN',.1,'netcon','ones(N_pre,N_post)'}; % connectivity matrix defined using a string that evalutes to a numeric matrix
s.connections(2).direction='E->I';
s.connections(2).mechanism_list={'iAMPA'};
s.connections(2).parameters={'tauD',2,'gSYN',.1,'netcon',ones(10,10)}; % connectivity set using a numeric matrix defined in script

vary = {'E','myshuffle',1:3};

% Test 1: Cluster flag off, compile flag on. Test parallel vs non-parallel
% Parallel
data=dsSimulate(s,'tspan',[0 200],'compile_flag',1,'verbose_flag',1,'random_seed','shuffle','parallel_flag',1,'vary',vary);
dsPlot2(data,'plot_type','raster','population','E')
```

It produces the following output (**sims 1 and 3 are the same**). 


![image](https://user-images.githubusercontent.com/5439305/33747765-df355426-db92-11e7-9438-c8500e30e431.png)


In contrast, setting parallel_flag to zero:

```
% Serial
data=dsSimulate(s,'tspan',[0 200],'compile_flag',1,'verbose_flag',1,'random_seed','shuffle','parallel_flag',0,'vary',vary);
dsPlot2(data,'plot_type','raster','population','E')
```

produces:



![image](https://user-images.githubusercontent.com/5439305/33747837-3534d8e2-db93-11e7-9a60-36fc19d7697d.png)

(all 3 sims are different)

**Comment by davestanley** [comment] 2017-12-08 02:16
This is not a function of the compiler (setting compile flag to 0 turns this off)

```
% Test 2: Cluster flag off, compile flag off. Test parallel
% Parallel
data=dsSimulate(s,'tspan',[0 200],'compile_flag',0,'verbose_flag',1,'random_seed','shuffle','parallel_flag',1,'vary',vary);
dsPlot2(data,'plot_type','raster','population','E')

```

![image](https://user-images.githubusercontent.com/5439305/33747966-e6889ade-db93-11e7-9b13-3925ca5d504b.png)

**Comment by davestanley** [comment] 2017-12-08 06:37
This is now complete.

@kupiqu , I disabled these changes from having an effect in Octave with a `strcmp(reportUI,'matlab')` clause. If Octave ever supports parallel computing in the future, if you start using pararrayfun, you can remove this (https://stackoverflow.com/questions/24970519/how-to-use-parallel-for-loop-in-octave-or-scilab).

**Comment by kupiqu** [comment] 2017-12-08 13:20
Please don't disable it for Octave. Octave supports parfor but it doesn't implement it (for now), which means that currently in Octave parfor = for, so there is no need to, and in fact it's better not to, so once this is implemented (if it is) it will work, or will need less tweaking...

**Comment by kupiqu** [comment] 2017-12-08 13:31
> if you start using pararrayfun, you can remove this (https://stackoverflow.com/questions/24970519/how-to-use-parallel-for-loop-in-octave-or-scilab).

I know about pararrayfun in the solver is not obvious, so better just to use parfor in Octave as it is and see whether they implement it or not. In any case this is transparent to users and DynaSim, so there is no reason to avoid using parfor in Octave.

The only issue I found is in reserving or checking the number of nodes. This is where one needs to be careful. There is some code about all this already that I added, did you see? I don't recall now the file...

**Comment by kupiqu** [comment] 2017-12-08 15:20
Dave,

Your addition is great. Thanks! 

But why do you set 

`strcmp(reportUI,'matlab')`

in

`if strcmp(options.random_seed,'shuffle') && strcmp(reportUI,'matlab')`

(dsSimulate.m line 677)

?

Did you check it in Octave and failed?

- If so, we should try to see whether there is a way to incorporate that functionality to Octave. That is the reason the rng wrapper was introduced by Jason and me in the first place, to have rng functionality working both in matlab and octave.

- If you didn't try, please don't restrict functionality in general for octave just because you think it is not going to work, please do check first (checking it in SCC is very easy, see https://github.com/DynaSim/DynaSim/wiki/Cluster-usage), or in case of doubt, please ask.

**Comment by davestanley** [comment] 2017-12-08 19:23
@kupiqu I have no way of checking octave, so disabled this code to err on the side of not breaking things. (I only disabled the new code I added, not the entire parfor block)

Feel free to enable this code for Octave if you like

**Comment by kupiqu** [comment] 2017-12-08 20:50
> @kupiqu I have no way of checking octave, so disabled this code to err on the side of not breaking things. (I only disabled the new code I added, not the entire parfor block)

@davestanley, point by point:

> @kupiqu I have no way of checking octave

Yes you have an easy way to check thinks in Octave, read: https://github.com/DynaSim/DynaSim/wiki/Cluster-usage and see issue #235

> disabled this code to err on the side of not breaking things. (I only disabled the new code I added, not the entire parfor block)

Your addition was great to solve a bug, but you disabled it for Octave. So, is the bug present when running your tests in Octave? Or, will it appear when/if parfor is implemented in Octave? If the answer to any of the two questions is yes, then you introduced buggy code.

If you fix it yourself, you will learn how to use DynaSim in Octave and will be trained to test new functionality you add (or bugs you fix) in the future

> Feel free to enable this code for Octave if you like

Guys, please understand that I don't have the time neither the intention of going after all commits to test and fix Octave compatibility (see issue #235).

We have two options here:

- Either we care and take DynaSim seriously in all its complexity, including Octave. 

- Or if we don't, then better we remove all Octave support in DynaSim now that the paper is not out yet.

This specific discusion is about octave, but could be applied to the wiki, the parallelization or anything else. I don't think "fix it if you like" is a valid answer to things we are responsible for. For instance:

- if a commit made by me breaks sth, and somebody makes me know, I won't answer, do it yourself if you like

- if I explained sth that can be useful and somebody asks me to add it to the wiki, I won't answer, do it yourself if you like

**Comment by erik-roberts** [comment] 2017-12-11 21:42
see my email to dev list

**Comment by davestanley** [comment] 2017-12-15 19:53
Yes, I'd like to support Octave and plan to fully test any new major features I add, including dsPlot2.

That being said,

1. Thanks for your input @kupiqu . About your comment:
> Your addition was great to solve a bug, but you disabled it for Octave. So, is the bug present when running your tests in Octave? Or, will it appear when/if parfor is implemented in Octave? If the answer to any of the two questions is yes, then you introduced buggy code.
- No. Failing to fix an already existing bug is not the same thing as introducing buggy code. 

2. More generally, for MATLAB features like parfor that don't have an Octave equivalent, I think it does not make sense to debug them under Octave. Rather, these features should be disabled and return an error message when an Octave user tries to run them. The reason being that it's impossible to properly test them, given that the functions (e.g. parfor) do not exist.

3. The link https://github.com/DynaSim/DynaSim/wiki/Cluster-usage seems to be broken (redirects to "Create new page")

**Comment by kupiqu** [comment] 2017-12-15 21:05
Sounds great Dave, thanks!

> More generally, for features like parfor that don't have an Octave equivalent, I think it does not make sense to debug them under Octave. Rather, these features should be disabled and return an error message when an Octave user tries to run them. The reason being is that it's impossible to properly test them, given that the required functions (e.g. parfor) do not exist in Octave. If/when they do become available, we can then do a complete review of the code for Octave compatibility.

Please note that PARFOR function DOES EXIST in GNU Octave

> The link https://github.com/DynaSim/DynaSim/wiki/Cluster-usage seems to be broken (redirects to "Create new page")

Mmm, weird, I will check it out... 

@erik-roberts I think someone moved wiki pages around, could this be the cause? I'm pretty newbie in what refers to wiki stuff, any idea how to fix the issue?

**Comment by kupiqu** [comment] 2017-12-15 21:06
Ok, I got it. The page was moved to https://github.com/DynaSim/DynaSim/wiki/HPC-Cluster-FAQ

**Comment by kupiqu** [comment] 2017-12-15 21:16
> No. Failing to fix an already existing bug is not the same thing as introducing buggy code.

Btw, about the 'buggy code' sentence, I should totally avoid saying that, it didn't bring anything minimally positive or constructive to the discussion, and I'm sorry about that...

**Comment by davestanley** [comment] 2017-12-15 21:23
Ok thanks, appreciate it.

>  PARFOR function DOES EXIST in GNU Octave
For this, you just mean that parfor redirects to for, right?

So instead of returning an error when invoking parallel_flag, the way I have it now just returns a warning. This will allow the demo code to still run, but it might take a long time to complete and might return errors elsewhere. Is this preferable, or would you rather an error just be returned outright when parallel_flag is run in Octave? I'd kind of prefer the latter for simplicity. Also, this is how we had it before I started working on parallel mode (e.g. DynaSim would return an error when parallel_flag == true).

**Comment by kupiqu** [comment] 2017-12-15 21:35
> For this, you just mean that parfor redirects to for, right?

Yes.

My point is that this choice was made by Octave developers, to add `parfor` keyword and redirect it to `for`. Then for simplicity what I propose (and as far as I recall, I implemented in DynaSim code) is to allow the use of `parallel_flag` in Octave  and use `parfor` in a transparent to the final user as it is the case for `parfor` in Octave outside DynaSim. 

So in summary, I would suggest not to trigger an error neither a warning, this is Octave's job to make, not ours, imo.

Also, this would avoid that Octave users see errors or many warnings when running dsDemos, or that parfor calls in Octave work one way outside and inside DynaSim code.

There are other functions in the parallel toolbox though that don't exist in Octave (to reserve or release a number of cores or to check how many there are), and those are functions that I disabled to avoid errors. This is the limitation that one needs to be careful with, imo.

Would you agree? What do you think?

**Comment by kupiqu** [comment] 2017-12-15 21:41
By the way, I tested the parallel_flag in Octave both in my laptop and in the cluster previously, it works slower as expected as `parfor = for` in Octave, but there are no other errors I am aware of...

**Comment by kupiqu** [comment] 2017-12-17 04:29
Perhaps, without defaulting to the error or warning function, we could still display an informative message for the Octave user clarifying that the multicore_flag does not have any effect yet in Octave, until parfor is properly implemented...

**Comment by kupiqu** [comment] 2017-12-18 20:59
> Perhaps, without defaulting to the error or warning function, we could still display an informative message for the Octave user clarifying that the multicore_flag does not have any effect yet in Octave, until parfor is properly implemented...

Done with merge #345 (still using parallel_flag though until we change its name everywhere...)

**Comment by erik-roberts** [comment] 2017-12-18 23:18
moved docs to https://github.com/DynaSim/DynaSim/wiki/Frequently-Asked-Questions#high-performance-computing-hpc-linux-cluster-faq

**Comment by kupiqu** [comment] 2017-12-19 17:15
Is there sthelse  to do here or should we close this issue?

**Comment by erik-roberts** [comment] 2018-01-09 23:30
dsWriteDynaSimSolver has an issue in the function `setup_randomseed` in dev and debug right now. it skips the check for shuffle. would someone please fix this when they have a moment.

**Closed** 2018-01-09 23:54 UTC
Labels: enhancement

**Comment by kupiqu** [comment] 2019-10-27 20:14
> dsWriteDynaSimSolver has an issue in the function `setup_randomseed` in debug right now. it skips the check for shuffle. would someone please fix this when they have a moment.

Done in #598
