### ISSUE TITLE
[BUG] error: regexp: invalid range in character class at position 3 of expression

### ISSUE THREAD

**Issue by edgithubONE** [DynaSim/DynaSim#691] opened 2023-04-05 11:05 UTC
**Describe the bug**
Using octave 7.3.0 gives no error but it is there with octave 8.1.0 newest version

**Expected behavior**
just run a varied parameter

**To Reproduce**

```
gNaFval = [100 200];
eqns={
      'dv/dt=Iapp+@current; {iNaF,iKDR,iM}; Iapp=5;  gNaF=100; gKDR=5; gM=1.5; v(0)=-70'
      };
vary = {'popl','gNaF',gNaFval};
varyset = dsVary2Modifications(vary);
data = dsSimulate(eqns, 'tspan',[0 2000],'save_data_flag',1,'study_dir','bursting','vary',vary);
```
```
error: regexp: invalid range in character class at position 3 of expression
error: called from
    dsVary2Modifications>expand_elem at line 238 column 8
    dsVary2Modifications>expand_vary at line 211 column 10
    dsVary2Modifications at line 168 column 24
```

**Versions:**
 - OS: windows 10
 - GNU Octave (platform and version): 8.1.0 (64bits)
 - DynaSym (release version / repository branch): latest version

**Additional context**
Any other context about the problem

**Comment by kupiqu** [comment] 2023-04-06 09:40
I will take a look

**Comment by kupiqu** [comment] 2023-04-06 10:14
Well, the issue is that you're trying to vary an object (`popl`) that doesn't exist in the mechanism.

Previous Octave versions would tolerate that as MATLAB does. Here I put the output of MATLAB R2022b does:

```MATLAB
gNaFval = [100 200];
eqns={
      'dv/dt=Iapp+@current; {iNaF,iKDR,iM}; Iapp=5;  gNaF=100; gKDR=5; gM=1.5; v(0)=-70'
      };
vary = {'popl','gNaF',gNaFval};
varyset = dsVary2Modifications(vary);
data = dsSimulate(eqns, 'tspan',[0 2000],'save_data_flag',1,'study_dir','bursting','vary',vary);

item =

    'popl'


item =

    'gNaF'


item =

    'popl'


item =

    'gNaF'

Warning: name of object to modify not found in populations or connections. 
> In dsApplyModifications>modify_specification (line 188)
In dsApplyModifications (line 116)
In dsSimulate/tryFn (line 961)
In dsSimulate (line 850) 
Warning: name of object to modify not found in populations or connections. 
> In dsApplyModifications>modify_specification (line 188)
In dsApplyModifications (line 116)
In dsSimulate/tryFn (line 961)
In dsSimulate (line 850)
```

In the changelog of Octave 8.1 (https://octave.org/NEWS-8.html), I can see the following:

> Summary of bugs fixed for version 8.1.0 (2023-01-22): Improved input validation and/or output handling for poly, pinv, patch, fill, fill3, qp, datevec, textscan, sub2ind, qr, airy, regexp, dec2bin, dec2hex, mean, and many others.

Which means that Octave detects that there is no regexp match and raises an error. Personally, I think this is the most appropriate behavior: one intends to vary a parameter that doesn't exist; it's likely due to a typo or because one invokes a wrong mechanism. 

It's then better to trigger an error so the user realizes about this; rather than triggering a warning, not checking it out, and analyzing the results as if the parameter was varied when it is actually not.

I'm closing now the issue as I don't consider it a bug.

**Comment by kupiqu** [comment] 2023-04-06 10:31
Well, while what I mentioned above is true, it seems that DynaSim somehow relies on this to apply vary modifications. I'm not familiar with the code behind how variations are implemented. I pin @jsherfey to see if we can find a fix that doesn't involve assuming non-existing objects. In the meantime I will try to find a workaround for the issue.

**Comment by kupiqu** [comment] 2023-04-06 10:50
I found the root issue and there was an easy fix. It ended up just being an issue with `-` in that regular expression, and the symbol needed to be escaped: `\-`

Now it works in Octave just fine. Will check in Matlab and if everything works, I will push the fix

**Comment by kupiqu** [comment] 2023-04-06 11:29
fixed in dev branch

**Closed as completed** 2023-04-06 11:29 UTC
Labels: bug
