### ISSUE TITLE
unable to run dsSimulate in MATLAB 2019b

### ISSUE THREAD

**Issue by kfchou** [DynaSim/DynaSim#575] opened 2019-09-18 20:19 UTC
Everything works fine when I was using MATLAB 2018a. I updated MATLAB to 2019b and received the following error:

Error: File: dsImportModel.m Line: 236 Column: 43
Invalid syntax for calling function 'varargin' on the path. Use a
valid syntax or explicitly initialize 'varargin' to make it a
variable.

Error in dsGenerateModel (line 241)
    [tmpmodel,tmpmap]=dsImportModel(equations,'namespace',PopScope,'ic_pop',specification.populations(i).name,'user_parameters',parameters);

Error in dsCheckModel (line 102)
  model=dsGenerateModel(model);

Error in dsSimulate (line 509)
model = dsCheckModel(model, varargin{:}); % handles conversion
when input is a string w/ equations or a DynaSim specification
structure

Error in myFunction(line 155)
data = dsSimulate(s,'time_limits',[dt time_end],
'solver',solverType, 'dt',dt,...

**Comment by kupiqu** [comment] 2019-10-09 22:13
Can you share a minimal example that triggers the issue?

**Comment by kfchou** [comment] 2019-10-10 14:14
Matlab deems line 236 in dsImportModel to have a syntax error:
`[model,map]=dsParseModelEquations(source, varargin{:});`

**Comment by kupiqu** [comment] 2019-10-10 14:16
I need a piece of code (e.g., your model) that I can run to trigger the error. Preferentially the example code should be as minimal as possible.

Thank you

**Comment by kupiqu** [comment] 2019-10-10 15:35
I understand, but what piece of which demo file is failing?

Of course I can install Matlab2019b and run all demo files myself (now that I know about them triggering the issue), but this is also about reporting issues properly (please do not take it personally), and having an example of code failing is essential for devs to rapidly reproducing the issue, and eventually fixing it.

**Comment by kfchou** [comment] 2019-10-10 17:14
Any call to dsSimulate will trigger the error. For example, the Lorentz equation demo will trigger it
`eqns={
  's=10; r=27; b=2.666'
  'dx/dt=s*(y-x);   x(0)=1'
  'dy/dt=r*x-y-x*z; y(0)=2'
  'dz/dt=-b*z+x*y;  z(0)=.5'
};
data=dsSimulate(eqns, 'time_limits',[0 100], 'solver','rk4');`

This error did not occur in Matlab2018b and only started after I updated to Matlab2019b. I traced the error to line 236 of dsImportModel. Matlab was not executing any code due to the syntax error it detected in dsImportModel. Sorry that it wasn't clear before.

**Comment by kupiqu** [comment] 2019-10-10 18:04
Thanks, will check it out

**Comment by kupiqu** [comment] 2019-10-10 19:24
Mmm, I am running Matlab 2019b in an external drive and get an error from this piece of code, but the error message is different than in your original report:

```
Error: Command syntax error see SIM command for details
         in dsSimulate/update_data (line 1197)
         in dsSimulate/tryFn (line 1184)
         in dsSimulate (line 830)
         in testDynaSim (line 9)
Error using dsSimulate/update_data (line 1197)
Command syntax error see SIM command for details

Error in dsSimulate/tryFn (line 1184)
        update_data; % concatenate data structures across simulations

Error in dsSimulate (line 830)
    tryFn(nargout)

Error in testDynaSim (line 9)
data=dsSimulate(eqns, 'time_limits',[0 100], 'solver','rk4'); - Show complete stack trace
```

So @kfchou, do you also see the same error for this example code? If so, it means that there is more than one error. Could you please confirm?

**Comment by kupiqu** [comment] 2019-10-10 20:33
I fixed the issue triggered by the example code you shared (dev branch), so I'm closing this issue.

If the original issue is not fixed by it, please reopen and attach a new example code specific for it.

**Closed by kupiqu** 2019-10-10 20:33 UTC
Labels: question

**Comment by kfchou** [comment] 2019-10-11 02:25
hmm that didn't fix the issue for me. I was able to resolve it by adding varargin as an input argument to the subfunction downloadModel() in dsImportModel.m, line 194
`function source=downloadModel(ModelID,**varargin**)`

similarly, add the input argument to the function call on line 49
`source=downloadModel(ModelID,**varargin**);`

Seems like there may be multiple syntax errors in the latest Matlab update. Will keep an eye out.

**Comment by kupiqu** [comment] 2019-10-11 02:34
Interesting. What DynaSim version do you use (1.0, master branch or dev)?

Also, is the error that you mention triggered with the same code that you
shared or a different one?

>

**Comment by resulal** [comment] 2020-05-11 05:24
I had the same error and fixed it. The problem was that the newer MATLAB versions require explicit declaration of all the variables that go into a parfor/spmd loops. Otherwise the compiler doesn't even allow for debugging. So, if you are using eval at somewhere, pay closer attention.

**Comment by mzachariou** [comment] 2021-07-26 13:05
Hi there, I just installed dynasim through github on a mac and I'm getting the same error while trying to run the tutorial in matlab R2020b:

eqns={
  's=10; r=27; b=2.666';
  'dx/dt=s*(y-x)';
  'dy/dt=r*x-y-x*z';
  'dz/dt=-b*z+x*y';
};
data=dsSimulate(eqns,'tspan',[0 100],'ic',[1 2 .5],'solver','rk4');

Error: File: dsImportModel.m Line: 236 Column: 43
Invalid syntax for calling function 'varargin' on the path. Use a valid syntax or explicitly
initialize 'varargin' to make it a variable.

Error in dsGenerateModel (line 241)
    [tmpmodel,tmpmap]=dsImportModel(equations,'namespace',PopScope,'ic_pop',specification.populations(i).name,'user_parameters',parameters);

Error in dsCheckModel (line 102)
  model=dsGenerateModel(model);

Error in dsSimulate (line 512)
model = dsCheckModel(model, varargin{:}); % handles conversion when input is a string w/
equations or a DynaSim specification structure

**Comment by jsherfey** [comment] 2021-07-26 21:48
Hello, Do you get the same error if you use the development version located
here: https://github.com/DynaSim/DynaSim/tree/dev

**Comment by mzachariou** [comment] 2021-07-27 07:20
Thank you, when I download the dev version as a zip it works fine (I had used git previously presumably a different version was downloaded through that).
