### ISSUE TITLE
Parameters without default values are not properly varied in Octave

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#234] opened 2017-10-07 08:39 UTC
In dsDemos, E.Iapp is not being varied but I->E.tauD is

**Comment by kupiqu** [comment] 2017-10-07 11:21
Ok, let's coordiante. Are you going to take a look to this or should I?

**Comment by kupiqu** [comment] 2017-10-07 23:38
Where do you see that? I checked data.E_Iapp and data.I_E_tauD and they are fine

**Comment by jsherfey** [comment] 2017-10-08 19:28
Ben: can you debug this using Octave: https://www.gnu.org/software/octave/download.html

**Comment by benpolletta** [comment] 2017-10-10 22:01
Is Octave installed on the scc? I can try debugging there.

**Comment by kupiqu** [comment] 2017-10-10 22:36
Not current stable version 4.2.1 of Octave, but version 4.0.2

I opened a ticket about it, but so far no response, perhaps tomorrow :-/

**Comment by kupiqu** [comment] 2017-10-10 22:38
I still don't know what the actual issue is. could you say about it?

**Comment by kupiqu** [comment] 2017-10-10 23:20
In the meanwhile this may ease (or not) Octave installation in Mac computers:

http://formulae.brew.sh/repos/Homebrew/homebrew-core/formula/octave

**Comment by jsherfey** [comment] 2017-10-10 23:34
I haven't been able to dive into the issue yet. The problem is that the following example from dsDemos should produce simulations for 9 unique parameter sets. Instead, it produces 9 simulations with only 3 unique parameter sets. My guess is that only one parameter is being varied, although it could be more complicated.


%% Setup Sparse Pyramidal-Interneuron-Network-Gamma (sPING)

% define equations of cell model (same for E and I populations)
eqns={
  'dv/dt=Iapp+@current+noise*randn(1,N_pop)'
  'monitor iGABAa.functions, iAMPA.functions'
};
% Tip: monitor all functions of a mechanism using: monitor MECHANISM.functions

% create DynaSim specification structure
s=[];
s.populations(1).name='E';
s.populations(1).size=80;
s.populations(1).equations=eqns;
s.populations(1).mechanism_list={'iNa','iK'};
s.populations(1).parameters={'Iapp',5,'gNa',120,'gK',36,'noise',40};
s.populations(2).name='I';
s.populations(2).size=20;
s.populations(2).equations=eqns;
s.populations(2).mechanism_list={'iNa','iK'};
s.populations(2).parameters={'Iapp',0,'gNa',120,'gK',36,'noise',40};
s.connections(1).direction='I->E';
s.connections(1).mechanism_list={'iGABAa'};
s.connections(1).parameters={'tauD',10,'gSYN',.1,'netcon','ones(N_pre,N_post)'};
s.connections(2).direction='E->I';
s.connections(2).mechanism_list={'iAMPA'};
s.connections(2).parameters={'tauD',2,'gSYN',.1,'netcon',ones(80,20)};

% Vary two parameters (run a simulation for all combinations of values)
vary={
  'E'   ,'Iapp',[0 10 20];      % amplitude of tonic input to E-cells
  'I->E','tauD',[5 10 15]       % inhibition decay time constant from I to E
  };
dsSimulate(s, 'save_data_flag', 1, 'study_dir', 'demo_sPING_3',...
                'vary', vary, 'verbose_flag', 1);
data=dsImport('demo_sPING_3');
dsPlot(data);

**Comment by kupiqu** [comment] 2017-10-10 23:42
Yes I checked the example out. In particular the code and results from the simulation (data), but so far I didn't see anything strange. Where do you see the 3 unique parameter sets repeated 3 times? I may have missed that part...

**Comment by kupiqu** [comment] 2017-10-11 02:22
Ok, I finally saw it. Although values in data.E_Iapp vary, Iapp values in data(i).model.specification.populations.parameters are not varied among the different i's

**Comment by kupiqu** [comment] 2017-10-11 03:44
Exactly same thing happens in Matlab, at least version 2014a

**Comment by jsherfey** [comment] 2017-10-11 04:00
It happens in Matlab 2017a, too. It might be a consequence of something I did last week. I'll debug this.

**Comment by jsherfey** [comment] 2017-10-11 04:01
It appeared to be working in Matlab 2017a before, but it was actually loading data that had been generated a while ago.

**Comment by kupiqu** [comment] 2017-10-11 04:05
it's sth in dsExportData

**Comment by kupiqu** [comment] 2017-10-11 04:10
it seems changes are not saved (even though they are simulated) because we are saving like this save(options.filename,vars{:}...) instead of save(options.filename,data,...)
could it be it?

**Comment by jsherfey** [comment] 2017-10-11 04:15
I don't think so. The data structure is not meant to be saved as a single variable. Instead, state variables in vars are saved individually in options.filename. The data structure is obtained by something like data=load(options.filename). That way individual state variables can be loaded using the matfile function without loading all the simulated data.

**Comment by kupiqu** [comment] 2017-10-11 04:27
Yes, I realized about that a bit late. Data is saved correctly (I checked individual mat files loaded also individually). Wondering if it could be sth in dsImport or sth

**Comment by kupiqu** [comment] 2017-10-11 04:51
So confused, everything seems to be ok now in Octave :/

I'll check it again in Matlab...

**Comment by jsherfey** [comment] 2017-10-11 05:40
I'm still getting the error. My guess is I->E.tauD is not being varied from simulation to simulation. That would suggest the problem is in dsApplyModifications, which I edited last week (I added support for mechanism-specific parameters and replaced unique and rng by wrappers using different functions for Matlab vs Octave).

**Comment by kupiqu** [comment] 2017-10-11 05:56
Could you pull changes from dev and try again? I don't think I changed anything relevant but somehow I cannot reproduce the issue anymore, neither in Octave nor in Matlab. Both parameters seem to be varied correctly...

**Comment by jsherfey** [comment] 2017-10-11 06:07
It's still not working for me. Try deleting all the demo_* directories in your working directory (set to ~/Documents/DynaSimData/demos in dsDemos) and testing the simulation again. If demo_sPING_3 contained working data from a previous run then that data would have been loaded and it would appear to be working even if it isn't.

**Comment by kupiqu** [comment] 2017-10-11 07:27
I always start from scratch :/

**Comment by jsherfey** [comment] 2017-10-12 23:07
I'm getting closer to figuring out the bug we discovered varying parameters. I don't think it has anything to do with the number of parameters varied or how the data were saved.

The problem occurs iff the varied parameters lack default values (e.g., parameters varied are present in the master equations but not assigned default values in the master equations). That is an unrecommended practice, but it is actually what was done in the dsDemos script.

Minimal example demonstrating the problem --

This worked:
dsPlot(dsSimulate('dv/dt=@current+I;{iNa,iK};I=0','vary',{'I',[0 5 10]}))

This didn't:
dsPlot(dsSimulate('dv/dt=@current+I;{iNa,iK}','vary',{'I',[0 5 10]}))
--> in this case, "I" was set to 0 and never updated again

I could solve this by having dsApplyModifications define the parameter in the master equations if it doesn't have a default value.

However, my remaining concern is that I don't know why the example in dsDemos worked at all before... 
and why the same version worked and didn't work for Salva on different runs, all starting from scratch.

That makes me think there's a different root problem, probably introduced by a previous commit. I will test a few versions at different points in time to localize the problematic commit.

I don't consider the bug urgent because parameters should be assigned default values. However, I would like DynaSim to support the other cases as well, or at least throw an error if a default value is not assigned.

**Comment by jsherfey** [comment] 2017-10-13 04:58
Note on how DynaSim handles parameters without default values:
If the value isn't set anywhere it'll return an error. However, if it's set in spec.pops.parameters, spec.cons.parameters, or using the vary option it used to take the value from there, with vary having priority over spec.*.parameters, and both having priority over default values set in mechanism or population-level equations.

It still works correctly for parameters without default values if they are set in spec.pops.parameters only, spec.cons.parameters only, or using the vary option with a single value. However, if multiple simulations are run varying one parameter, the value gets set on the first run and is not varied again. Surprisingly, if two or more parameters are varied, the first parameter is actually varied across simulations, but all other parameters are fixed to their first value in the set.

**Comment by kupiqu** [comment] 2017-10-13 10:21
Two things:

1) I would propose that DynaSim internally initiliazes defined parameters that don't have a value, as NAN and a warning is raised to let the final user know that this is discouraged. We would need to be careful teting that it would work in all ways and conditions.

2) From what you said, I have a clue to know why sometimes works sometimes it doesn't. Testing now and will tell if I can confirm.

**Comment by benpolletta** [comment] 2017-10-20 17:46
Any luck with this bug? I'd be happy to take a look... Jason, where does assignment of parameter values happen (i.e., which programs do the prioritization you mentioned two comments ago)?

**Comment by jsherfey** [comment] 2017-10-21 05:47
This issue has been resolved for Matlab only in commit e4f8cbf155e16893a550d22341ff65498ba3657f.

The problem arose in commit b980961ac2ed556c732e26af7b99fe48f2a5800c (on 29-Sep-2017) when "-" was escaped in the pattern for classifying parameters in dsClassifyEquation(). That was done for compatability with GNU Octave. I added a reportUI check to use the old working pattern if running Matlab, otherwise use the still-broken Octave-compatible version.

The change in parameter pattern for Octave-compatibility introduced an error when varying parameters initialized using key/value pairs in .pops.parameters. In that case, dsCheckSpecification() automatically appends "key=value" to .pops.equations; after that, dsApplyModifications() fails to override the automatically-generated "default" value (in .pops.equations) with the simulation-specific value from 'vary'. 

This needs to be investigated further to achieve compatibility in Octave.

**Comment by kupiqu** [comment] 2017-10-21 18:50
Oops, sorry I introduced the bug. I'll try to see if there is an alternative way to fix it...

**Comment by kupiqu** [comment] 2017-10-21 19:45
Actually the problem is of matlab. According to https://regex101.com/ there is a pattern error in the matlab expression but not in the octave expression.

However, there is no match with I=+0.0000000 for the correct match expression and that's why the parameters are not varied.

I will try to get the proper regular expression that makes a proper match here and will apply it to both Matlab and Octave...

**Comment by kupiqu** [comment] 2017-10-21 19:59
Ok, I fixed it by adding the missing "+"

I have no idea why matlab accepts wrong regular expressions and why it matched the expression without adding the plus :/

**Closed** 2017-10-21 20:05 UTC
Labels: bug
